[project]
name = "example-tool-server"
version = "0.1.0"
description = "An example tool server."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "universal-tool-server>=0.0.3",
]

[dependency-groups]
test = [
    "ruff>=0.9.9",
]
